In [1]:
# Create a NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# Checking NumPy Version
import numpy as np

print(np.__version__)


2.0.0


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Use a tuple to create a NumPy array
import numpy as np

arr = np.array((1, 2, 3, 4, 5))
print(arr)


[1 2 3 4 5]


In [7]:
# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. 
# Each value in an array is a 0-D array.
import numpy as np

arr = np.array(42)
print(arr)


42


In [8]:
# 1-D Arrays
# An array that has 0-D arrays as its elements is 
# called uni-dimensional or 1-D array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [9]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is 
# called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.
# NumPy has a whole sub module dedicated towards matrix 
# operations called numpy.mat

# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3-D arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
# These are often used to represent a 3rd order tensor.
# Create a 3-D array with two 2-D arrays, both containing 
# two arrays with the values 1,2,3 and 4,5,6:

import numpy as np


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
# Check Number of Dimensions
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.

# Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)



[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
# Access Array Elements
# Array indexing is the same as accessing an array element.
# The indexes in NumPy arrays start with 0, meaning that the 
# first element has index 0, and the second has index 1 etc.
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])


1


In [15]:
# the second element from the following array
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [16]:
# third and fourth elements from the 
# following array and add them
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [18]:
# Access 2-D Arrays
# To access elements from 2-D arrays we can use comma separated 
# integers representing the dimension and the index of the element.

# Think of 2-D arrays like a table with rows and columns, where 
# the dimension represents the row and the index represents the column.
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

# Access the element on the 2nd row, 5th column
print('5th element on 2nd row: ', arr[1, 4])


2nd element on 1st row:  2
5th element on 2nd row:  10


In [19]:
# Access 3-D Arrays
# To access elements from 3-D arrays we can use comma 
# separated integers representing the dimensions and the 
# index of the element.

# Access the third element of the second array of the first array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])


6


In [21]:
# Negative Indexing
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [22]:
# Slicing arrays
# Slice elements from index 1 to index 5 from the following array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


In [23]:
# Slice elements from index 4 to the end of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [24]:
# Slice elements from the beginning to index 4
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [25]:
# Slice from the index 3 from the end to index 1 from the end
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [26]:
# Use the step value to determine the step of the slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [27]:
# Return every other element from the entire array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [28]:
# Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [29]:
# From both elements, return index 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [30]:
# From both elements, slice index 1 to index 4 
# (not included), this will return a 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [33]:
# Checking the Data Type of an Array
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [32]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

In [34]:
# Creating Arrays With a Defined Data Type
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [35]:
# Create an array with data type 4 bytes integer
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [36]:
# What if a Value Can Not Be Converted
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [37]:
# Converting Data Type on Existing Arrays
# The best way to change the data type of an existing array, 
# is to make a copy of the array with the astype() method.

# The astype() function creates a copy of the array, and 
# allows you to specify the data type as a parameter.
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [38]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [39]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [40]:
# The main difference between a copy and a view of an array is that the 
# copy is a new array, and the view is just a view of the original array.

# The copy owns the data and any changes made to the copy will not affect 
# original array, and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect 
# the original array, and any changes made to the original array will affect the view.

# Make a copy, change the original array, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [41]:
# Make a view, change the original array, and display both arrays

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)



[42  2  3  4  5]
[42  2  3  4  5]


In [42]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [44]:
# Shape of an Array
# NumPy arrays have an attribute called shape that returns a 
# tuple with each index having the number of corresponding elements.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [45]:
# Create an array with 5 dimensions using ndmin using a 
# vector with values 1,2,3,4 and verify that last dimension has value 4
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [46]:
# Reshaping arrays
# Reshaping means changing the shape of an array.
# The shape of an array is the number of elements in each dimension.
# By reshaping we can add or remove dimensions or 
# change number of elements in each dimension.


# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
# Convert the following 1-D array with 12 
# elements into a 3-D array.
# The outermost dimension will have 2 arrays that 
# contains 3 arrays, each with 2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [48]:
# Try converting 1D array with 8 elements to a 2D array 
# with 3 elements in each dimension (will raise an error):

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [50]:
# Returns Copy or View
# Check if the returned array is a copy or a view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


In [51]:
# Unknown Dimension
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number 
# for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
# Flattening the arrays
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.

# Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [53]:
# Iterating Arrays
# Iterating means going through elements one by one.

# As we deal with multi-dimensional arrays in numpy, 
# we can do this using basic for loop of python.

# If we iterate on a 1-D array it will go through 
# each element one by one.

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [55]:
# Iterating 2-D Arrays
# In a 2-D array it will go through all the rows.


arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [56]:
# If we iterate on a n-D array it will go 
# through n-1th dimension one by one.
# To return the actual values, the scalars, 
# we have to iterate the arrays in each dimension.

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [57]:
# Iterating 3-D Arrays
# In a 3-D array it will go through all the 2-D arrays.
# Iterate on the elements of the following 3-D array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [58]:
# To return the actual values, the scalars, 
# we have to iterate the arrays in each dimension.
# Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [61]:
# Iterating Arrays Using nditer()
# The function nditer() is a helping function that can be used 
# from very basic to very advanced iterations. It solves some basic 
# issues which we face in iteration, lets go through it with examples.
# Iterating on Each Scalar Element
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [62]:
# Iterating Array With Different Data Types

# We can use op_dtypes argument and pass it the expected 
# datatype to change the datatype of elements while iterating.

# NumPy does not change the data type of the element in-place 
# (where the element is in array) so it needs some other space 
# to perform this action, that extra space is called buffer, and 
# in order to enable it in nditer() we pass flags=['buffered'].

# Iterate through the array as a string

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [63]:
# Iterating With Different Step Size
# We can use filtering and followed by iteration.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [64]:
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.

# Sometimes we require corresponding index of the element while iterating, 
# the ndenumerate() method can be used for those usecases.

# Enumerate on following 1D arrays elements:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3


In [65]:
# Enumerate on following 2D array's elements:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [69]:

# Joining means putting contents of two or more arrays in a single array.
# In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
# We pass a sequence of arrays that we want to join to the concatenate() function, 
# along with the axis. If axis is not explicitly passed, it is taken as 0.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [70]:
# Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [77]:
# Stacking Along Rows
# Stacking is same as concatenation, the only difference 
# is that stacking is done along a new axis.
# We can concatenate two 1-D arrays along the second axis 
# which would result in putting them one over the other, ie. stacking.

# We pass a sequence of arrays that we want to join to the stack() 
# method along with the axis. If axis is not explicitly passed it is taken as 0.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [80]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [81]:
# Stacking Along Columns
# NumPy provides a helper function: vstack()  to stack along columns.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)


[[1 2 3]
 [4 5 6]]


In [82]:
# Stacking Along Height (depth)
# NumPy provides a helper function: dstack() to stack 
# along height, which is the same as depth.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
