In [1]:
# Create a NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# Checking NumPy Version
import numpy as np

print(np.__version__)


2.0.0


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Use a tuple to create a NumPy array
import numpy as np

arr = np.array((1, 2, 3, 4, 5))
print(arr)


[1 2 3 4 5]


In [7]:
# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. 
# Each value in an array is a 0-D array.
import numpy as np

arr = np.array(42)
print(arr)


42


In [8]:
# 1-D Arrays
# An array that has 0-D arrays as its elements is 
# called uni-dimensional or 1-D array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [9]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is 
# called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.
# NumPy has a whole sub module dedicated towards matrix 
# operations called numpy.mat

# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3-D arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
# These are often used to represent a 3rd order tensor.
# Create a 3-D array with two 2-D arrays, both containing 
# two arrays with the values 1,2,3 and 4,5,6:

import numpy as np


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
# Check Number of Dimensions
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.

# Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)



[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
# Access Array Elements
# Array indexing is the same as accessing an array element.
# The indexes in NumPy arrays start with 0, meaning that the 
# first element has index 0, and the second has index 1 etc.
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])


1


In [15]:
# the second element from the following array
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [16]:
# third and fourth elements from the 
# following array and add them
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [18]:
# Access 2-D Arrays
# To access elements from 2-D arrays we can use comma separated 
# integers representing the dimension and the index of the element.

# Think of 2-D arrays like a table with rows and columns, where 
# the dimension represents the row and the index represents the column.
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

# Access the element on the 2nd row, 5th column
print('5th element on 2nd row: ', arr[1, 4])


2nd element on 1st row:  2
5th element on 2nd row:  10


In [19]:
# Access 3-D Arrays
# To access elements from 3-D arrays we can use comma 
# separated integers representing the dimensions and the 
# index of the element.

# Access the third element of the second array of the first array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])


6


In [21]:
# Negative Indexing
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [22]:
# Slicing arrays
# Slice elements from index 1 to index 5 from the following array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


In [23]:
# Slice elements from index 4 to the end of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [24]:
# Slice elements from the beginning to index 4
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [25]:
# Slice from the index 3 from the end to index 1 from the end
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [26]:
# Use the step value to determine the step of the slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [27]:
# Return every other element from the entire array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [28]:
# Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [29]:
# From both elements, return index 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [30]:
# From both elements, slice index 1 to index 4 
# (not included), this will return a 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [33]:
# Checking the Data Type of an Array
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [32]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

In [34]:
# Creating Arrays With a Defined Data Type
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [35]:
# Create an array with data type 4 bytes integer
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [36]:
# What if a Value Can Not Be Converted
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [37]:
# Converting Data Type on Existing Arrays
# The best way to change the data type of an existing array, 
# is to make a copy of the array with the astype() method.

# The astype() function creates a copy of the array, and 
# allows you to specify the data type as a parameter.
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [38]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [39]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [40]:
# The main difference between a copy and a view of an array is that the 
# copy is a new array, and the view is just a view of the original array.

# The copy owns the data and any changes made to the copy will not affect 
# original array, and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect 
# the original array, and any changes made to the original array will affect the view.

# Make a copy, change the original array, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [41]:
# Make a view, change the original array, and display both arrays

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)



[42  2  3  4  5]
[42  2  3  4  5]


In [42]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [44]:
# Shape of an Array
# NumPy arrays have an attribute called shape that returns a 
# tuple with each index having the number of corresponding elements.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [45]:
# Create an array with 5 dimensions using ndmin using a 
# vector with values 1,2,3,4 and verify that last dimension has value 4
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [46]:
# Reshaping arrays
# Reshaping means changing the shape of an array.
# The shape of an array is the number of elements in each dimension.
# By reshaping we can add or remove dimensions or 
# change number of elements in each dimension.


# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
# Convert the following 1-D array with 12 
# elements into a 3-D array.
# The outermost dimension will have 2 arrays that 
# contains 3 arrays, each with 2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [48]:
# Try converting 1D array with 8 elements to a 2D array 
# with 3 elements in each dimension (will raise an error):

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [50]:
# Returns Copy or View
# Check if the returned array is a copy or a view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


In [51]:
# Unknown Dimension
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number 
# for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
# Flattening the arrays
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.

# Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [53]:
# Iterating Arrays
# Iterating means going through elements one by one.

# As we deal with multi-dimensional arrays in numpy, 
# we can do this using basic for loop of python.

# If we iterate on a 1-D array it will go through 
# each element one by one.

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [55]:
# Iterating 2-D Arrays
# In a 2-D array it will go through all the rows.


arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [56]:
# If we iterate on a n-D array it will go 
# through n-1th dimension one by one.
# To return the actual values, the scalars, 
# we have to iterate the arrays in each dimension.

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [57]:
# Iterating 3-D Arrays
# In a 3-D array it will go through all the 2-D arrays.
# Iterate on the elements of the following 3-D array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [58]:
# To return the actual values, the scalars, 
# we have to iterate the arrays in each dimension.
# Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [61]:
# Iterating Arrays Using nditer()
# The function nditer() is a helping function that can be used 
# from very basic to very advanced iterations. It solves some basic 
# issues which we face in iteration, lets go through it with examples.
# Iterating on Each Scalar Element
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [62]:
# Iterating Array With Different Data Types

# We can use op_dtypes argument and pass it the expected 
# datatype to change the datatype of elements while iterating.

# NumPy does not change the data type of the element in-place 
# (where the element is in array) so it needs some other space 
# to perform this action, that extra space is called buffer, and 
# in order to enable it in nditer() we pass flags=['buffered'].

# Iterate through the array as a string

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [63]:
# Iterating With Different Step Size
# We can use filtering and followed by iteration.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [64]:
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.

# Sometimes we require corresponding index of the element while iterating, 
# the ndenumerate() method can be used for those usecases.

# Enumerate on following 1D arrays elements:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3


In [65]:
# Enumerate on following 2D array's elements:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [69]:

# Joining means putting contents of two or more arrays in a single array.
# In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
# We pass a sequence of arrays that we want to join to the concatenate() function, 
# along with the axis. If axis is not explicitly passed, it is taken as 0.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [70]:
# Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [77]:
# Stacking Along Rows
# Stacking is same as concatenation, the only difference 
# is that stacking is done along a new axis.
# We can concatenate two 1-D arrays along the second axis 
# which would result in putting them one over the other, ie. stacking.

# We pass a sequence of arrays that we want to join to the stack() 
# method along with the axis. If axis is not explicitly passed it is taken as 0.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [80]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [81]:
# Stacking Along Columns
# NumPy provides a helper function: vstack()  to stack along columns.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)


[[1 2 3]
 [4 5 6]]


In [82]:
# Stacking Along Height (depth)
# NumPy provides a helper function: dstack() to stack 
# along height, which is the same as depth.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [83]:
# Splitting NumPy Arrays
# Splitting is reverse operation of Joining.
# Joining merges multiple arrays into one and Splitting 
# breaks one array into multiple.
# We use array_split() for splitting arrays, we pass it the 
# array we want to split and the number of splits.

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [84]:
# If the array has less elements than required, 
# it will adjust from the end accordingly.

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [86]:
# We also have the method split() available but it will not adjust 
# the elements when elements are less in source array for splitting 
# like in example above, array_split() worked properly but split() 
# would fail.

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [87]:
# Splitting 2-D Arrays
# Use the same syntax when splitting 2-D arrays.
# Use the array_split() method, pass in the array you want 
# to split and the number of splits you want to do.
# Split the 2-D arr ay into three 2-D arrays.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [88]:
# The example above returns three 2-D arrays.
# Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [89]:
# The example below also returns three 2-D arrays, but 
# they are split along the row (axis=1).

# Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [90]:
# An alternate solution is using hsplit() opposite of hstack()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [91]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [92]:
# Find the indexes where the values are even:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [93]:
# Find the indexes where the values are odd:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [94]:
# Search Sorted
# There is a method called searchsorted() which performs a binary search 
# in the array, and returns the index where the specified value would 
# be inserted to maintain the search order.
# The searchsorted() method is assumed to be used on sorted arrays.

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)

print(x)

1


In [95]:
# Search From the Right Side
# By default the left most index is returned, but we can 
# give side='right' to return the right most index instead.

# Find the indexes where the value 7 should be inserted, starting from the right:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')

print(x)


2


In [96]:
# Multiple Values
# To search for more than one value, use an array with the specified values.

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [97]:
# Sorting Arrays
# Sorting means putting elements in an ordered sequence.
# Ordered sequence is any sequence that has an order corresponding 
# to elements, like numeric or alphabetical, ascending or descending.
# The NumPy ndarray object has a function called sort(), that will 
# sort a specified array.
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [98]:
# Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [99]:
# Sort a boolean array:

arr = np.array([True, False, True])
print(np.sort(arr))


[False  True  True]


In [100]:
# Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both 
# arrays will be sorted:
# Sort a 2-D array:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [101]:
# Filtering Arrays
# Getting some elements out of an existing array and 
# creating a new array out of them is called filtering.
# A boolean index list is a list of booleans corresponding 
# to indexes in the array.

# If the value at an index is True that element is contained in 
# the filtered array, if the value at that index is False that 
# element is excluded from the filtered array.

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]

print(newarr)

[41 43]


In [104]:
# Creating the Filter Array

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [105]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [106]:
# Create a filter array that will return only values higher than 42:

arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [107]:
# Create a filter array that will return only even elements 
# from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [108]:
# NumPy ufuncs
# ufuncs stands for "Universal Functions" and they are NumPy 
# functions that operate on the ndarray object

# Why  ufuncs
# ufuncs are used to implement vectorization in NumPy which is 
# way faster than iterating over elements.
# They also provide broadcasting and additional methods like 
# reduce, accumulate etc. that are very helpful for computation.

# ufuncs also take additional arguments, like:
# where boolean array or condition defining where the operations 
# should take place.
# dtype defining the return type of elements.
# out output array where the return value should be copied.

# What is Vectorization
# Converting iterative statements into a vector based operation 
# is called vectorization.
# It is faster as modern CPUs are optimized for such operations.

# Without ufunc, we can use Python's built-in zip() method:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)


[5, 7, 9, 11]


In [109]:
# With ufunc, we can use the add() function:

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [110]:
# How To Create Your Own ufunc
# To create your own ufunc, you have to define a function, like you 
# do with normal functions in Python, then you add it to your NumPy 
# ufunc library with the frompyfunc() method.

# The frompyfunc() method takes the following arguments:
# function - the name of the function.
# inputs - the number of input arguments (arrays).
# outputs - the number of output arrays.

# Create your own ufunc for addition:

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))


[6 8 10 12]


In [112]:
# Check if a Function is a ufunc
# Check if a function is a ufunc:

print(type(np.add))


<class 'numpy.ufunc'>


In [113]:
# If it is not a ufunc, it will return another type, like 
# this built-in NumPy function for joining two or more arrays:

print(type(np.concatenate))


<class 'numpy._ArrayFunctionDispatcher'>


In [114]:
# If the function is not recognized at all, it will return an error:

print(type(np.blahblah))


AttributeError: module 'numpy' has no attribute 'blahblah'

In [115]:
# To test if the function is a ufunc in an if statement, use the 
# numpy.ufunc value (or np.ufunc if you use np as an alias for numpy):

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [116]:
# Simple Arithmetic
# The add() function sums the content of two arrays, 
# and return the results in a new array.

import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
print(newarr)


[30 32 34 36 38 40]


In [117]:
# Subtraction
# Subtract the values in arr2 from the values in arr1:

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)
print(newarr)

[-10  -1   8  17  26  35]


In [118]:
# Multiplication

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)
print(newarr)

[ 200  420  660  920 1200 1500]


In [119]:
# Division

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)
print(newarr)


[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [120]:
# Power
# The power() function rises the values from the first array to the 
# power of the values of the second array, and return the results 
# in a new array.

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)
print(newarr)


[         1000       3200000     729000000 6553600000000          2500
             0]


In [121]:
# Remainder

# Both the mod() and the remainder() functions return the remainder 
# of the values in the first array corresponding to the values in 
# the second array, and return the results in a new array.

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)
print(newarr)



[ 1  6  3  0  0 27]


In [122]:
# Return the remainders:

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [123]:
# Quotient and Mod
# The divmod() function return both the quotient and the the mod. 
# The return value is two arrays, the first array contains 
# the quotient and second array contains the mod.

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)
print(newarr)


(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [124]:
# Absolute Values
# Both the absolute() and the abs() functions do the same absolute 
# operation element-wise but we should use absolute() to avoid 
# confusion with python's inbuilt math.abs()

arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [126]:
# Rounding Decimals
# There are primarily five ways of rounding off decimals in NumPy:
# truncation
# fix
# rounding
# floor
# ceil

# Truncation
# Remove the decimals, and return the float number closest to zero. 
# Use the trunc() and fix() functions.

arr = np.trunc([-3.1666, 3.6667])
print(arr)


[-3.  3.]


In [127]:
# Same example, using fix():

arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [128]:
# Rounding
# The around() function increments preceding digit or decimal 
# by 1 if >=5 else do nothing.
# E.g. round off to 1 decimal point, 3.16666 is 3.2

arr = np.around(3.1666, 2)
print(arr)


3.17


In [129]:
# Floor

# The floor() function rounds off decimal to nearest lower integer.
# E.g. floor of 3.166 is 3.

arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [130]:
# Ceil
# The ceil() function rounds off decimal to nearest upper integer.
# E.g. ceil of 3.166 is 4.

arr = np.ceil([-3.1666, 3.6667])
print(arr)


[-3.  4.]


In [132]:
# Logs
# NumPy provides functions to perform log at the base 2, e and 10.
# Log at Base 2
# Use the log2() function to perform log at the base 2.

# Find log at base 2 of all elements of following array:


arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [134]:
# Log at Base 10
# Use the log10() function to perform log at the base 10.
# Find log at base 10 of all elements of following array:

arr = np.arange(1, 10)
print(np.log10(arr))


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [135]:
# Natural Log, or Log at Base e

arr = np.arange(1, 10)
print(np.log(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [136]:
# Log at Any Base

from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))


1.7005483074552052


In [137]:
# Summations
# Addition is done between two arguments whereas 
# summation happens over n elements.

# Add the values in arr1 to the values in arr2:

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)
print(newarr)


[2 4 6]


In [138]:
# Sum the values in arr1 and the values in arr2:

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])
print(newarr)


12


In [139]:
# Summation Over an Axis
# If you specify axis=1, NumPy will sum the numbers in each array.
# Perform summation in the following array over 1st axis:

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [140]:
# Cummulative Sum
# Cummulative sum means partially adding the elements in array.
# E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
# Perfom partial sum with the cumsum() function.
# Perform cummulative summation in the following array:

arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)


[1 3 6]


In [141]:
# Products
# To find the product of the elements in an array, 
# use the prod() function.
# Find the product of the elements of this array:

arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

24


In [142]:
# Find the product of the elements of two arrays:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])
print(x)


40320


In [143]:
# Product Over an Axis

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)
print(newarr)


[  24 1680]


In [144]:
# Cummulative Product
# Cummulative product means taking the product partially.
# E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]
# Perfom partial sum with the cumprod() function.

# Take cummulative product of all elements for following array:

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)
print(newarr)


[   5   30  210 1680]


In [145]:
# Differences
# A discrete difference means subtracting two successive elements.
# E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]
# To find the discrete difference, use the diff() function.

arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)

print(newarr)


[  5  10 -20]


In [147]:
# We can perform this operation repeatedly by giving parameter n.
# E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would 
# be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once 
# more, with the new result: [1-1, 1-1] = [0, 0]

# Compute discrete difference of the following array twice:

arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)

print(newarr)


[  5 -30]


In [148]:
# Finding LCM (Lowest Common Multiple)
# The Lowest Common Multiple is the smallest number 
# that is a common multiple of two numbers.

# Find the LCM of the following two numbers:

num1 = 4
num2 = 6

x = np.lcm(num1, num2)
print(x)


12


In [149]:
# Finding LCM in Arrays
# To find the Lowest Common Multiple of all values in an array, 
# you can use the reduce() method.

# The reduce() method will use the ufunc, in this case the lcm() function, 
# on each element, and reduce the array by one dimension.

# Find the LCM of the values of the following array:

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)
print(x)

18


In [150]:
# Find the LCM of all values of an array where the array 
# contains all integers from 1 to 10:

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)
print(x)


2520
