In [1]:
# Create a NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# Checking NumPy Version
import numpy as np

print(np.__version__)


2.0.0


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Use a tuple to create a NumPy array
import numpy as np

arr = np.array((1, 2, 3, 4, 5))
print(arr)


[1 2 3 4 5]


In [7]:
# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. 
# Each value in an array is a 0-D array.
import numpy as np

arr = np.array(42)
print(arr)


42


In [8]:
# 1-D Arrays
# An array that has 0-D arrays as its elements is 
# called uni-dimensional or 1-D array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [9]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is 
# called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.
# NumPy has a whole sub module dedicated towards matrix 
# operations called numpy.mat

# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3-D arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
# These are often used to represent a 3rd order tensor.
# Create a 3-D array with two 2-D arrays, both containing 
# two arrays with the values 1,2,3 and 4,5,6:

import numpy as np


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
# Check Number of Dimensions
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.

# Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)



[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
# Access Array Elements
# Array indexing is the same as accessing an array element.
# The indexes in NumPy arrays start with 0, meaning that the 
# first element has index 0, and the second has index 1 etc.
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])


1


In [15]:
# the second element from the following array
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [16]:
# third and fourth elements from the 
# following array and add them
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [18]:
# Access 2-D Arrays
# To access elements from 2-D arrays we can use comma separated 
# integers representing the dimension and the index of the element.

# Think of 2-D arrays like a table with rows and columns, where 
# the dimension represents the row and the index represents the column.
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

# Access the element on the 2nd row, 5th column
print('5th element on 2nd row: ', arr[1, 4])


2nd element on 1st row:  2
5th element on 2nd row:  10


In [19]:
# Access 3-D Arrays
# To access elements from 3-D arrays we can use comma 
# separated integers representing the dimensions and the 
# index of the element.

# Access the third element of the second array of the first array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])


6


In [21]:
# Negative Indexing
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [22]:
# Slicing arrays
# Slice elements from index 1 to index 5 from the following array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


In [23]:
# Slice elements from index 4 to the end of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [24]:
# Slice elements from the beginning to index 4
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [25]:
# Slice from the index 3 from the end to index 1 from the end
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [26]:
# Use the step value to determine the step of the slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [27]:
# Return every other element from the entire array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [28]:
# Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [29]:
# From both elements, return index 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [30]:
# From both elements, slice index 1 to index 4 
# (not included), this will return a 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [33]:
# Checking the Data Type of an Array
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [32]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

In [34]:
# Creating Arrays With a Defined Data Type
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [35]:
# Create an array with data type 4 bytes integer
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [36]:
# What if a Value Can Not Be Converted
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [37]:
# Converting Data Type on Existing Arrays
# The best way to change the data type of an existing array, 
# is to make a copy of the array with the astype() method.

# The astype() function creates a copy of the array, and 
# allows you to specify the data type as a parameter.
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [38]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [39]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [40]:
# The main difference between a copy and a view of an array is that the 
# copy is a new array, and the view is just a view of the original array.

# The copy owns the data and any changes made to the copy will not affect 
# original array, and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect 
# the original array, and any changes made to the original array will affect the view.

# Make a copy, change the original array, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [41]:
# Make a view, change the original array, and display both arrays

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)



[42  2  3  4  5]
[42  2  3  4  5]


In [42]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [44]:
# Shape of an Array
# NumPy arrays have an attribute called shape that returns a 
# tuple with each index having the number of corresponding elements.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [45]:
# Create an array with 5 dimensions using ndmin using a 
# vector with values 1,2,3,4 and verify that last dimension has value 4
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
